name: Build Flatpak

on:
  push:
    tags:
      - "*"
    branches:
      - "dev"

  workflow_dispatch:
    inputs:
      branch:
        description: 'Checkout branch'
        required: false
      tag:
        description: 'Checkout tag'
        required: false

jobs:
  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y flatpak-builder flatpak

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}

      - name: Set Flatpak manifest branch
        run: |
          TARGET_REF="${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}"
          REF_TYPE="branch"
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            REF_TYPE="tag"
          fi
          sed -i "/url: https:\/\/github.com\/sanny32\/OpenModScan.git/{
            n
            /branch:\|tag:\|commit:/d
            a\
            \        $REF_TYPE: $TARGET_REF
          }" .flatpak/io.github.sanny32.omodscan.yaml

      - name: Prepare Flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub org.kde.Sdk//6.9

      - name: Build Flatpak
        run: |
          cd .flatpak
          flatpak info org.kde.Sdk//6.9
          flatpak-builder --repo=repo --force-clean --verbose build io.github.sanny32.omodscan.yaml
          flatpak build-bundle repo io.github.sanny32.omodscan.flatpak io.github.sanny32.omodscan stable

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: io.github.sanny32.omodscan.flatpak
          path: |
            .flatpak/io.github.sanny32.omodscan.flatpak