name: Build Flatpak

on:
  push:
    tags:
      - "*"
    branches:
      - "dev"

  workflow_dispatch:
    inputs:
      branch:
        description: 'Checkout branch'
        required: false
      tag:
        description: 'Checkout tag'
        required: false

jobs:
  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Set REF env
        run: |
          echo "REF=${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Build Flatpak
        run: |
          cd .flatpak
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.kde.Sdk//6.9
          flatpak install -y flathub org.flatpak.Builder
          flatpak run org.flatpak.Builder --repo=repo --force-clean --verbose --default-branch=dev build io.github.sanny32.omodscan.yaml
          flatpak build-bundle repo io.github.sanny32.omodscan.flatpak io.github.sanny32.omodscan stable

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenModScan-flatpak
          path: |
            io.github.sanny32.omodscan.flatpak