name: Build Flatpak

on:
  push:
    tags:
      - "*"
    branches:
      - "dev"

  workflow_dispatch:
    inputs:
      branch:
        description: 'Checkout branch'
        required: false
      tag:
        description: 'Checkout tag'
        required: false

jobs:
  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged

    steps:
      - name: Set REF env
        run: |
          echo "REF=${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Restore Flatpak cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/flatpak-builder
          key: flatpak-builder-${{ runner.os }}-${{ hashFiles('.flatpak/*.yaml') }}

      - name: Prepare Flatpak YAML
        run: |
          export REF=$REF
          envsubst < .flatpak/io.github.sanny32.omodscan.yaml > .flatpak/io.github.sanny32.omodscan.build.yaml

      - name: Build Flatpak
        run: |
          mkdir -p build-repo build-dir
          flatpak-builder --repo=build-repo build-dir .flatpak/io.github.sanny32.omodscan.yaml
          flatpak build-bundle build-repo io.github.sanny32.omodscan.flatpak io.github.sanny32.omodscan

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenModScan-flatpak
          path: |
            io.github.sanny32.omodscan.flatpak